import { test, expect } from '@playwright/test';

test.describe('New Reports — View Report modal', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/notifications');
    await page.getByTestId('new-reports-button').click();
  });

  test('New Reports drawer shows REPORT READY notifications', async ({ page }) => {
    const drawer = page.getByTestId('new-reports-drawer');
    const subtypeLabels = drawer.getByTestId('notification-subtype');
    await expect(subtypeLabels.first()).toHaveText('Report ready');
    await expect(drawer.getByTestId('notification-card')).toHaveCount(3);
  });

  test('clicking "View report" CTA opens the report modal', async ({ page }) => {
    const drawer = page.getByTestId('new-reports-drawer');
    await drawer.getByTestId('notification-cta').first().click();
    const dialog = page.getByTestId('report-detail-dialog');
    await expect(dialog).toBeVisible();
    await expect(dialog.getByText('Q1 2025 Portfolio Performance Report')).toBeVisible();
  });

  test('modal shows report metadata (format, scope, status chips)', async ({ page }) => {
    const drawer = page.getByTestId('new-reports-drawer');
    await drawer.getByTestId('notification-cta').first().click();
    const dialog = page.getByTestId('report-detail-dialog');
    await expect(dialog.getByText('PDF').first()).toBeVisible();
    await expect(dialog.getByText('portfolio', { exact: true })).toBeVisible();
    await expect(dialog.getByText('ready', { exact: true })).toBeVisible();
  });

  test('modal close button dismisses the dialog', async ({ page }) => {
    const drawer = page.getByTestId('new-reports-drawer');
    await drawer.getByTestId('notification-cta').first().click();
    const dialog = page.getByTestId('report-detail-dialog');
    await expect(dialog).toBeVisible();
    await dialog.getByRole('button', { name: /close/i }).first().click();
    await expect(dialog).not.toBeVisible();
  });

  test('Download button triggers report generation toast', async ({ page }) => {
    const drawer = page.getByTestId('new-reports-drawer');
    await drawer.getByTestId('notification-cta').first().click();
    const dialog = page.getByTestId('report-detail-dialog');
    await dialog.getByRole('button', { name: /download/i }).click();
    await expect(page.getByText('Report generation started').first()).toBeVisible();
  });

  test('opening report marks notification as read', async ({ page }) => {
    const drawer = page.getByTestId('new-reports-drawer');
    await drawer.getByTestId('notification-cta').first().click();
    const dialog = page.getByTestId('report-detail-dialog');
    // Close modal and verify card is still present (read state changed)
    await dialog.getByRole('button', { name: /close/i }).first().click();
    await expect(drawer.getByTestId('notification-card').first()).toBeVisible();
  });

  test('modal shows GENERATED section label', async ({ page }) => {
    const drawer = page.getByTestId('new-reports-drawer');
    await drawer.getByTestId('notification-cta').first().click();
    await expect(page.getByTestId('report-detail-dialog').getByText('GENERATED', { exact: true })).toBeVisible();
  });

  test('modal shows GENERATED BY user name', async ({ page }) => {
    // rpt-001 generatedByUserId: usr-001 → Alexandru Ionescu
    const drawer = page.getByTestId('new-reports-drawer');
    await drawer.getByTestId('notification-cta').first().click();
    const dialog = page.getByTestId('report-detail-dialog');
    await expect(dialog.getByText('GENERATED BY')).toBeVisible();
    await expect(dialog.getByText('Alexandru Ionescu')).toBeVisible();
  });

  test('modal shows COVERS section with building IDs', async ({ page }) => {
    // rpt-001 covers bld-001 through bld-006
    const drawer = page.getByTestId('new-reports-drawer');
    await drawer.getByTestId('notification-cta').first().click();
    const dialog = page.getByTestId('report-detail-dialog');
    await expect(dialog.getByText('COVERS')).toBeVisible();
    await expect(dialog.getByText(/bld-001/)).toBeVisible();
  });

  test('Download button label reflects report format', async ({ page }) => {
    // rpt-001 is PDF format
    const drawer = page.getByTestId('new-reports-drawer');
    await drawer.getByTestId('notification-cta').first().click();
    await expect(page.getByTestId('report-detail-dialog').getByRole('button', { name: /download pdf/i })).toBeVisible();
  });

  test('second report card opens correct report in modal', async ({ page }) => {
    // ntf-002 → rpt-002 "Bucharest Office Tower – Energy Audit 2025"
    const drawer = page.getByTestId('new-reports-drawer');
    await drawer.getByTestId('notification-cta').nth(1).click();
    const dialog = page.getByTestId('report-detail-dialog');
    await expect(dialog).toBeVisible();
    await expect(dialog.getByText('Bucharest Office Tower – Energy Audit 2025')).toBeVisible();
  });
});
